# 자주쓰이는 Numpy 함수 정리

이번에는 넘파이에서 자주쓰이는 함수를 정리해 보겠습니다. 이전글에 있었던 reshape를 포함해 다음에 나오는 함수들도 매우 자주 사용하는 함수들이니 많은 도움이 될거라 생각합니다.

In [ ]:
copy,flatten,round,sort,std,sum,transpose

# 타입에 관한 함수

### 1.astype

array에 담긴 데이터의 타입을 변경시켜주는 함수입니다.

In [5]:
import numpy as np
a = np.array([1,2,3,4]).astype(np.uint32)
a.dtype

dtype('uint32')

### 2.tolist

array를 list로 바꿔줘야하는 경우가 종종 있는데 이때 사용하는 함수입니다.

In [6]:
a = np.array([1,2,3,4])
a.tolist()
a.dtype

dtype('int32')

# 통계 관련 변수

# # min,max,mean,std,var

# np.mean(array,axis = ? )

정확한 워딩이 아니지만 평균, 표준편차를 쉽게 구할수 있도록 numpy 에서 제공하는
함수들의 사용법을 알아보겠습니다.

In [15]:
# a = np.array([1,2,3,4,5])
# print(a.min)
# print(np.max(a))
# a.mean()
# print(np.median(a))

a = np.random.normal(size=(1000,10)) # 1000개의 열이고 10개의 칼럼 
np.std(a,axis=0) 

array([0.9740106 , 1.00227271, 1.00776845, 0.9703867 , 1.03692962,
       1.00691034, 0.96456281, 0.9443746 , 0.9722908 , 0.97915626])

[1 2 3 4]
[ 37.  74. 111. 148.]
[100 200 300 400]
[ 44.69899328  89.39798655 134.09697983 178.79597311]
[ 1998.  7992. 17982. 31968.]


[  1  10 100]
[  2.5  25.  250. ]
[  4  40 400]
[  1.11803399  11.18033989 111.80339887]
[1.25e+00 1.25e+02 1.25e+04]


사용 예시를 보면 1차원일경우 가장 직관적인 값을 리턴합니다.
2차원 이상의 경우 axis를 설정해줄수 있는데 쉽게 말해서 축을 결정해서 계산을 해냅니다. 가로, 세로 또는 그 이상의 차원이 존재할 경우에 다양하게 지정할 수 있습니다.

# 조건함수 : any,all,where

# Ex : np.where(array>=3,True일때값,Flase일때 값)


any : 특정 조건을 만족하는 원소가 있으면 True를 리턴합니다.

In [18]:
a = np.array(range(1,11))
np.any(a>0)

True

all : 모든 원소가 조건을 만족하면 True를 리턴합니다.

In [19]:
a = np.array(range(1,11))
np.all(a>0)

True

where : 조건에 맞는 인덱스만 리턴합니다.


In [21]:
a = np.array(range(1,11)).reshape(2,5)
a.g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

where(조건, True일때 출력값, false일때 출력값)

[    1    10   100  1000 10000]
[    0    10   100  1000 10000]
[    0     0   100  1000 10000]
[    0     0     0  1000 10000]
[    0     0     0     0 10000]


[ True  True  True  True  True]
[False  True  True  True  True]
[False False  True  True  True]
[False False False  True  True]
[False False False False  True]


# 인덱스를 리턴하는 함수 : argmax,argmin

최대값 또는 최소값의 인덱스가 궁금할때 사용가능합니다.

In [27]:
a
a.argmax()

5
0


[1 0 0 0 0 0]
[2 2 2 1 1 1]


[5 5 0]
[0 2 5]


5
17
